[build]
  publish = "dist"
  command = "grunt build"

[[redirects]]
  from = "/tw"
  to = "/.netlify/functions/redirect?https://twitter.com/parkeragee"

[[redirects]]
  from = "/ig"
  to = "/.netlify/functions/redirect?https://instagram.com/parkeragee"

[[redirects]]
  from = "/pay"
  to = "/.netlify/functions/redirect?https://pay.sullylabs.com"

[[redirects]]
  from = "/mail"
  to = "/.netlify/functions/redirect?https://mail.parkeragee.com"

[[redirects]]
  from = "/count"
  to = "/.netlify/functions/redirect?url=https://google.com"
