[build]
  publish = "dist"
  command = "grunt build"
  functions = "/functions/"

[[redirects]]
  from = "/tw"
  to = "https://twitter.com/parkeragee?source=urlshortener"

[[redirects]]
  from = "/ig"
  to = "https://instagram.com/parkeragee?source=urlshortener"

[[redirects]]
  from = "/pay"
  to = "https://pay.sullylabs.com?source=urlshortener"

[[redirects]]
  from = "/mail"
  to = "https://mail.parkeragee.com?source=urlshortener"

[[redirects]]
  from = "/count"
  to = "/.netlify/functions/redirect?url=https://google.com"
