[build]
  publish = "dist"
  command = "grunt build"

[[redirects]]
  from = "/tw"
  to = "https://twitter.com/parkeragee"

[[redirects]]
  from = "/ig"
  to = "https://instagram.com/parkeragee"

[[redirects]]
  from = "/pay"
  to = "https://pay.sullylabs.com"

[[redirects]]
  from = "/mail"
  to = "https://mail.parkeragee.com"

[[redirects]]
  from = "/count"
  to = "https://google.com"
